import { createClient } from "@supabase/supabase-js";

const fail=(error,status)=>Response.json({error},{status});
const eventKinds=new Set(["wedding","first_birthday","birthday","baby_shower","bridal_shower","anniversary","housewarming","graduation","corporate","party","other","gathering","custom","opening","milestone_birthday"]);
const eventKindOf=(value)=>eventKinds.has(String(value||""))?String(value):null;
const clean=(value)=>{const s=value&&typeof value==="object"&&!Array.isArray(value)?value:{},text=(key,max=500)=>String(s[key]||"").slice(0,max);return {
child_name:text("child_name",80),child_last_name:text("child_last_name",80),child_first_name:text("child_first_name",80),birth_date:text("birth_date",40),parent1_name:text("parent1_name",80),parent2_name:text("parent2_name",80),
parents_intro_enabled:s.parents_intro_enabled===true,parent1_photo_url:text("parent1_photo_url",2000),parent1_intro:text("parent1_intro",160),parent2_photo_url:text("parent2_photo_url",2000),parent2_intro:text("parent2_intro",160),
parent1_phone:text("parent1_phone",80),parent2_phone:text("parent2_phone",80),person1_phone:text("person1_phone",80),host_phone:text("host_phone",80),manager_phone:text("manager_phone",80),host1_phone:text("host1_phone",80),host2_phone:text("host2_phone",80),host_name:text("host_name",80),manager_name:text("manager_name",80),host1_name:text("host1_name",80),host2_name:text("host2_name",80),person1_name:text("person1_name",80),event_title:text("event_title",160),
groom_name:text("groom_name",80),groom_last_name:text("groom_last_name",80),groom_first_name:text("groom_first_name",80),bride_name:text("bride_name",80),bride_last_name:text("bride_last_name",80),bride_first_name:text("bride_first_name",80),
groom_phone:text("groom_phone",80),bride_phone:text("bride_phone",80),groom_father_name:text("groom_father_name",80),groom_mother_name:text("groom_mother_name",80),bride_father_name:text("bride_father_name",80),bride_mother_name:text("bride_mother_name",80),
groom_father_phone:text("groom_father_phone",80),groom_mother_phone:text("groom_mother_phone",80),bride_father_phone:text("bride_father_phone",80),bride_mother_phone:text("bride_mother_phone",80),
event_date:text("event_date",40),event_time:text("event_time",40),venue:text("venue",200),venue_address:text("venue_address",500),venue_building:text("venue_building",200),venue_detail:text("venue_detail",200),
transport_public_enabled:s.transport_public_enabled===true,transport_public:text("transport_public",2000),transport_car_enabled:s.transport_car_enabled===true,transport_car:text("transport_car",2000),transport_parking_enabled:s.transport_parking_enabled===true,transport_parking:text("transport_parking",2000),
groom_bank:text("groom_bank",80),groom_account:text("groom_account",100),groom_account_holder:text("groom_account_holder",80),bride_bank:text("bride_bank",80),bride_account:text("bride_account",100),bride_account_holder:text("bride_account_holder",80),
invitation_message:text("invitation_message",2000),rsvp_enabled:s.rsvp_enabled!==false,guestbook_enabled:s.guestbook_enabled!==false,
notice_enabled:s.notice_enabled===true,notice_title:text("notice_title",80),notice_body:text("notice_body",3000),notice_image_url:text("notice_image_url",2000),
gallery_images:Array.isArray(s.gallery_images)?s.gallery_images.filter(x=>typeof x==="string"&&x).slice(0,20).map(x=>x.slice(0,2000)):[],
timeline_enabled:s.timeline_enabled===true,timeline_items:Array.isArray(s.timeline_items)?s.timeline_items.slice(0,6).map((item,index)=>({id:String(item?.id||`sample-${index+1}`).slice(0,100),date:String(item?.date||"").slice(0,40),text:String(item?.text||"").slice(0,80),photoUrl:String(item?.photoUrl||item?.photo_url||"").slice(0,2000)})):[]
};};
async function admin(request){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,publishableKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!url||!key||!publishableKey)return {error:"관리자 서비스를 준비하지 못했어요.",status:503};if(!token)return {error:"로그인이 필요합니다.",status:401};const service=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}),{data:{user},error}=await service.auth.getUser(token);if(error||!user)return {error:"로그인이 만료되었습니다.",status:401};const verifier=createClient(url,publishableKey,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{autoRefreshToken:false,persistSession:false}}),{data:isAdmin,error:adminError}=await verifier.rpc("is_admin");if(adminError)return {error:"관리자 권한을 확인하지 못했어요.",status:500};if(isAdmin!==true)return {error:"관리자만 접근할 수 있습니다.",status:403};return {client:service};}
export async function GET(request){const a=await admin(request);if(a.error)return fail(a.error,a.status);const kind=eventKindOf(new URL(request.url).searchParams.get("eventKind"));if(!kind)return fail("지원하지 않는 행사 유형입니다.",400);const {data,error}=await a.client.from("completed_template_sample_defaults").select("sample_content").eq("id",kind).maybeSingle();if(error)return fail("행사유형별 샘플 콘텐츠를 불러오지 못했어요.",500);if(data)return Response.json({event_kind:kind,sample_content:clean(data.sample_content)});return Response.json({event_kind:kind,sample_content:clean(null)});}
export async function PUT(request){const a=await admin(request);if(a.error)return fail(a.error,a.status);const body=await request.json().catch(()=>null),kind=eventKindOf(body?.event_kind),sample_content=clean(body?.sample_content);if(!kind)return fail("지원하지 않는 행사 유형입니다.",400);const table=a.client.from("completed_template_sample_defaults");const {error}=await table.upsert({id:kind,sample_content},{onConflict:"id"});if(error)return fail(`행사유형별 샘플 콘텐츠를 저장하지 못했어요. (${error.message||"DB 오류"})`,500);return Response.json({event_kind:kind,sample_content});}
