"use client";

import { useEffect, useRef, useState } from "react";
import { getSupabaseBrowserClient } from "../../../lib/supabase/browser";
import { captureRenderedHero } from "../../../lib/capture-element";
import InvitationRenderer from "../../../components/invitation/invitation-renderer";

const displayLabels=[["eyebrow","상단 초대 문구"],["eventLabel","행사 문구"],["title","행사 제목 / 이름"],["relations","관계 정보"],["detail","상세 정보"],["note","추가 문구"],["schedule","날짜 / 시간"],["venue","장소"]];
const defaultDisplay=Object.fromEntries(displayLabels.map(([key])=>[key,true]));
const defaultConfig={mode:"photo",aspectRatio:"4:5",positionX:50,positionY:50,textYPercent:50,scheduleFontSize:11,zoom:1,overlayColor:"#000000",overlayOpacity:0,headerVisible:true,mastheadVisible:true,mastheadText:"",display:defaultDisplay};
const empty={name:"",preset_key:"",description:"",status:"draft",is_visible:false,sort_order:0,config:defaultConfig};
const field={display:"grid",gap:5,minWidth:0};
const input={width:"100%",boxSizing:"border-box",minHeight:40,padding:"8px 10px",border:"1px solid #d7c5ba",borderRadius:7};
const card={border:"1px solid #eadfd8",borderRadius:14,padding:16,background:"#fff"};

export default function HeroPresetsPage(){
 const [state,setState]=useState({loading:true,error:"",presets:[]}); const [editing,setEditing]=useState(null); const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(""); const [assets,setAssets]=useState([]); const [assetBusy,setAssetBusy]=useState(""); const heroPreviewRef=useRef(null);
 const auth=async()=>{const client=getSupabaseBrowserClient();const {data:{session}}=client?await client.auth.getSession():{data:{}};if(!session)throw new Error("로그인이 필요합니다.");return {Authorization:`Bearer ${session.access_token}`};};
 const load=async()=>{const response=await fetch("/api/admin/hero-presets",{headers:await auth()});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Hero 프리셋 목록을 불러오지 못했어요.");setState({loading:false,error:"",presets:result.presets||[]});};
 useEffect(()=>{load().catch((e)=>setState({loading:false,error:e.message,presets:[]}));},[]);
 const loadAssets=async(id)=>{const response=await fetch(`/api/admin/hero-presets/assets?heroPresetId=${encodeURIComponent(id)}`,{headers:await auth()});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Hero Asset을 불러오지 못했어요.");setAssets(result.assets||[]);};
 const open=(preset=null)=>{setEditing(preset?.id||"new");setAssets([]);if(preset?.id)loadAssets(preset.id).catch((e)=>setNotice(e.message));setForm(preset?{name:preset.name,preset_key:preset.preset_key,description:preset.description||"",status:preset.status,is_visible:preset.is_visible,sort_order:preset.sort_order,config:{...defaultConfig,...preset.config,display:{...defaultDisplay,...preset.config?.display}}}:{...empty,config:{...defaultConfig,display:{...defaultDisplay}}});setNotice("");};
 const setConfig=(key,value)=>setForm((current)=>({...current,config:{...current.config,[key]:value}}));
 const uploadAsset=async(type,file)=>{if(!file||editing==="new"||assetBusy)return;setAssetBusy(type);setNotice("");try{const size=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(new Error("이미지 크기를 확인하지 못했어요."));image.src=URL.createObjectURL(file);});const data=new FormData();data.append("heroPresetId",editing);data.append("assetType",type);data.append("file",file);data.append("width",String(size.width));data.append("height",String(size.height));const response=await fetch("/api/admin/hero-presets/assets",{method:"POST",headers:await auth(),body:data});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Hero 이미지를 업로드하지 못했어요.");await loadAssets(editing);setNotice(type==="thumbnail"?"Hero 썸네일을 저장했습니다.":"Hero 프레임 이미지를 저장했습니다.");}catch(e){setNotice(e.message);}finally{setAssetBusy("");}};
 const captureThumbnail=async()=>{if(editing==="new"||assetBusy)return;setAssetBusy("thumbnail");setNotice("");try{const {blob,width,height}=await captureRenderedHero(heroPreviewRef.current,{width:600});if(!(blob instanceof Blob)||!blob.size)throw new Error("캡처 이미지가 비어 있어요.");const file=new File([blob],`${form.preset_key||"hero"}-thumbnail.png`,{type:"image/png"});const data=new FormData();data.append("heroPresetId",editing);data.append("assetType","thumbnail");data.append("file",file);data.append("width",String(width));data.append("height",String(height));const headers=await auth();const response=await fetch("/api/admin/hero-presets/assets",{method:"POST",headers,body:data});const raw=await response.text();let result={};try{result=raw?JSON.parse(raw):{};}catch{}if(!response.ok)throw new Error(result.error||`썸네일 업로드 실패 (HTTP ${response.status})`);await loadAssets(editing);setNotice("현재 Hero 미리보기를 선택 화면 썸네일로 저장했습니다.");}catch(e){console.error("Hero thumbnail capture failed",e);setNotice(`썸네일 캡처 실패: ${e instanceof Error&&e.message?e.message:"알 수 없는 오류"}`);}finally{setAssetBusy("");}};
 const activeFrame=assets.find((item)=>item.asset_type==="hero_frame"&&item.is_active)||null;
 const liveConfig={hero:{...form.config,frameAssetId:activeFrame?.id||null}};
 const liveAssets=activeFrame?.url?{[activeFrame.id]:activeFrame.url}:{};
 const liveInvitation={eventKind:"wedding",groom:"경원",bride:"보람",groomFatherName:"박영채",groomMotherName:"김이순",brideFatherName:"이규수",brideMotherName:"김덕임",date:"2026-10-17",time:"12:30",venue:"디어데이 웨딩홀",venueAddress:"서울특별시 중구 세종대로 110",message:"소중한 분들을 모시고 새로운 시작을 함께하려 합니다.",coverPhotoUrl:"/templates/modern-001/preview.png"};
 const save=async(e)=>{e.preventDefault();if(saving)return;setSaving(true);setNotice("");try{const response=await fetch("/api/admin/hero-presets",{method:editing==="new"?"POST":"PATCH",headers:{...(await auth()),"Content-Type":"application/json"},body:JSON.stringify({...form,preset_key:form.preset_key.trim(),...(editing!=="new"?{id:editing}:{})})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"저장하지 못했어요.");await load();setEditing(null);setNotice("Hero 프리셋을 저장했습니다.");}catch(e){setNotice(e.message);}finally{setSaving(false);}};
 return <main style={{maxWidth:980,margin:"0 auto",padding:"32px 16px 64px"}}><p className="section-kicker">ADMIN · HERO PRESETS</p><h1>Hero 프레임 관리</h1><p>Hero는 사진·프레임·텍스트 배치만 관리합니다. 본문 배경과 장식은 기존 템플릿 관리에서 계속 관리합니다.</p><p><a href="/admin/templates">← 본문 테마 관리</a></p>
 {state.loading?<p>불러오는 중이에요.</p>:state.error?<p className="payment-error">{state.error}</p>:<>
 {!editing&&<button type="button" className="save-button" onClick={()=>open()}>새 Hero 프리셋</button>}{notice&&<p role="status">{notice}</p>}
 {editing?<form onSubmit={save} style={{...card,display:"grid",gap:14,marginTop:16}}><h2 style={{margin:0}}>{editing==="new"?"새 Hero 프리셋":"Hero 프리셋 수정"}</h2>
 <label style={field}>이름<input style={input} required maxLength={100} value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label>
 <label style={field}>Preset key<input style={input} required pattern="[a-z0-9](?:[a-z0-9]|_|-){2,79}" disabled={editing!=="new"} value={form.preset_key} onChange={(e)=>setForm({...form,preset_key:e.target.value.trim()})}/></label>
 <label style={field}>설명<textarea style={input} rows={3} maxLength={2000} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}>
 <label style={field}>상태<select style={input} value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="draft">제작중</option><option value="on_sale">사용중</option><option value="stopped">사용중지</option></select></label>
 <label style={field}>정렬순서<input style={input} type="number" min={-10000} max={10000} value={form.sort_order} onChange={(e)=>setForm({...form,sort_order:Number(e.target.value)})}/></label>
 <label style={{display:"flex",alignItems:"center",gap:7}}><input type="checkbox" checked={form.is_visible} onChange={(e)=>setForm({...form,is_visible:e.target.checked})}/> 사용자 선택에 노출</label></div>
 <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(300px,390px)",gap:16,alignItems:"start"}}>
 <div><fieldset style={{border:"1px solid #eadfd8",borderRadius:10,padding:12}}><legend>Hero 레이아웃</legend><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:10}}>
 <label style={field}>표현 방식<select style={input} value={form.config.mode} onChange={(e)=>setConfig("mode",e.target.value)}><option value="photo">사진 중심형</option><option value="frame">컨셉 프레임형</option><option value="illustration">포스터/일러스트형</option></select></label>
 <label style={field}>비율<select style={input} value={form.config.aspectRatio} onChange={(e)=>setConfig("aspectRatio",e.target.value)}>{["4:5","1:1","3:4","16:9"].map(v=><option key={v}>{v}</option>)}</select></label>
 {[["positionX","사진 X 위치 %",0,100,1],["positionY","사진 Y 위치 %",0,100,1],["textYPercent","텍스트 Y 위치 %",0,100,1],["scheduleFontSize","날짜 글자 크기",8,24,1],["zoom","사진 Zoom",.5,2,.05],["overlayOpacity","Overlay 투명도",0,1,.05]].map(([key,label,min,max,step])=><label style={field} key={key}>{label}<input style={input} type="number" min={min} max={max} step={step} value={form.config[key]} onChange={(e)=>setConfig(key,Number(e.target.value))}/></label>)}
 <label style={field}>Overlay 색상<input style={input} type="color" value={form.config.overlayColor} onChange={(e)=>setConfig("overlayColor",e.target.value)}/></label>
 <label style={field}>상단 문구<input style={input} maxLength={60} value={form.config.mastheadText} onChange={(e)=>setConfig("mastheadText",e.target.value)}/></label>
 </div><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:12}}><label><input type="checkbox" checked={form.config.headerVisible} onChange={(e)=>setConfig("headerVisible",e.target.checked)}/> DearDay 표시</label><label><input type="checkbox" checked={form.config.mastheadVisible} onChange={(e)=>setConfig("mastheadVisible",e.target.checked)}/> 상단 행사문구 표시</label></div>
 <fieldset style={{marginTop:12,border:"1px solid #eadfd8",borderRadius:8}}><legend>Hero 표시 항목</legend><div style={{display:"flex",gap:12,flexWrap:"wrap"}}>{displayLabels.map(([key,label])=><label key={key}><input type="checkbox" checked={form.config.display[key]} onChange={(e)=>setConfig("display",{...form.config.display,[key]:e.target.checked})}/>{label}</label>)}</div></fieldset></fieldset></div>
 <aside style={{position:"sticky",top:16,border:"1px solid #eadfd8",borderRadius:12,padding:10,background:"#f8f3ef"}}><strong style={{display:"block",marginBottom:8}}>Hero LIVE PREVIEW</strong><p style={{fontSize:12,color:"#806f66",margin:"0 0 8px"}}>설정값이 저장 전에도 즉시 반영됩니다.</p><div ref={heroPreviewRef} className="hero-admin-live-preview" style={{width:"100%",overflow:"hidden",borderRadius:10,background:"#fff"}}><InvitationRenderer invitation={liveInvitation} eventKind="wedding" templateConfig={liveConfig} templateAssets={liveAssets}/><style>{`.hero-admin-live-preview .invitation-template > :not(.classic-masthead):not(.classic-hero){display:none!important}.hero-admin-live-preview .invitation-template{min-height:0!important}.hero-admin-live-preview .classic-hero{margin-bottom:0!important}`}</style></div></aside></div>
 {editing!=="new"&&<fieldset style={{border:"1px solid #eadfd8",borderRadius:10,padding:12}}><legend>Hero 썸네일 캡처</legend><p style={{marginTop:0,color:"#806f66",fontSize:13}}>오른쪽 Hero LIVE PREVIEW에 표시된 현재 모습을 그대로 캡처합니다. 저장하지 않은 설정 변경도 반영됩니다.</p><button type="button" className="save-button" disabled={!!assetBusy} onClick={captureThumbnail}>{assetBusy==="thumbnail"?"캡처 저장 중...":"현재 Hero 썸네일 캡처"}</button></fieldset>}
 {editing!=="new"&&<fieldset style={{border:"1px solid #eadfd8",borderRadius:10,padding:12}}><legend>Hero 이미지 Asset</legend><p style={{marginTop:0,color:"#806f66",fontSize:13}}>Hero 선택 화면용 썸네일과 실제 Hero 프레임을 각각 등록합니다. 새 파일을 올리면 기존 활성 이미지는 자동으로 교체됩니다.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}>{[["thumbnail","선택 화면 썸네일"],["hero_frame","실제 Hero 프레임"]].map(([type,label])=>{const asset=assets.find((item)=>item.asset_type===type&&item.is_active);return <div key={type} style={{border:"1px solid #eadfd8",borderRadius:10,padding:10}}><strong>{label}</strong>{asset?.url?<img src={asset.url} alt="" style={{display:"block",width:"100%",maxHeight:220,objectFit:"contain",margin:"10px 0",borderRadius:8,background:"#f7f3f0"}}/>:<p style={{fontSize:12,color:"#8d7a70"}}>등록된 이미지 없음</p>}<label className="save-button" style={{display:"inline-block",cursor:assetBusy?"wait":"pointer"}}>{assetBusy===type?"업로드 중...":asset?"교체 업로드":"이미지 업로드"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={!!assetBusy} style={{display:"none"}} onChange={(e)=>{const file=e.target.files?.[0];e.target.value="";if(file)uploadAsset(type,file);}}/></label></div>})}</div></fieldset>}
 {editing==="new"&&<p style={{margin:0,color:"#806f66",fontSize:13}}>기본정보를 먼저 저장한 뒤 썸네일과 Hero 프레임 이미지를 등록할 수 있습니다.</p>}
 <div style={{display:"flex",gap:8}}><button className="save-button" disabled={saving}>{saving?"저장 중...":"저장"}</button><button type="button" className="save-button" disabled={saving} onClick={()=>setEditing(null)}>취소</button></div></form>:
 <div style={{display:"grid",gap:12,marginTop:16}}>{state.presets.length?state.presets.map((preset)=><article key={preset.id} style={card}><h2 style={{margin:"0 0 8px"}}>{preset.name}</h2><p style={{margin:"4px 0"}}>{preset.preset_key} · {preset.status==="on_sale"?"사용중":preset.status==="stopped"?"사용중지":"제작중"} · {preset.is_visible?"노출":"숨김"}</p><button type="button" className="save-button" onClick={()=>open(preset)}>수정하기</button></article>):<p>등록된 Hero 프리셋이 없습니다.</p>}</div>}</>}</main>;
}
