"use client";

import { useEffect, useRef, useState } from "react";
import { getSupabaseBrowserClient } from "../../../lib/supabase/browser";
import InvitationRenderer from "../../../components/invitation/invitation-renderer";
import { HERO_FONTS, HERO_FONT_STYLESHEET } from "../../../lib/hero-fonts";

const displayLabels=[["eyebrow","상단 초대 문구"],["eventLabel","행사 문구"],["title","행사 제목 / 이름"],["relations","관계 정보"],["detail","상세 정보"],["note","추가 문구"],["schedule","날짜 / 시간"],["venue","장소"]];
const defaultDisplay=Object.fromEntries(displayLabels.map(([key])=>[key,true]));
const defaultConfig={mode:"photo",aspectRatio:"4:5",positionX:50,positionY:50,textYPercent:50,scheduleFontSize:11,zoom:1,overlayColor:"#000000",overlayOpacity:0,headerVisible:true,mastheadVisible:true,mastheadText:"",display:defaultDisplay,textLayers:[]};
const empty={name:"",preset_key:"",description:"",status:"draft",is_visible:false,sort_order:0,config:defaultConfig};
const field={display:"grid",gap:5,minWidth:0};
const input={width:"100%",boxSizing:"border-box",minHeight:40,padding:"8px 10px",border:"1px solid #d7c5ba",borderRadius:7};
const card={border:"1px solid #eadfd8",borderRadius:14,padding:16,background:"#fff"};

export default function HeroPresetsPage(){
 const [fontLibraryOpen,setFontLibraryOpen]=useState(false);
 const [state,setState]=useState({loading:true,error:"",presets:[]}); const [editing,setEditing]=useState(null); const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(""); const [assets,setAssets]=useState([]); const [assetBusy,setAssetBusy]=useState(""); const heroPreviewRef=useRef(null); const [samplePhoto,setSamplePhoto]=useState(""); const samplePhotoRef=useRef("");
 useEffect(()=>()=>{if(samplePhotoRef.current)URL.revokeObjectURL(samplePhotoRef.current);},[]);
 const changeSamplePhoto=(file)=>{if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setNotice("JPG, PNG, WebP 사진만 업로드할 수 있어요.");return;}if(file.size>15*1024*1024){setNotice("15MB 이하 사진을 선택해 주세요.");return;}const url=URL.createObjectURL(file);if(samplePhotoRef.current)URL.revokeObjectURL(samplePhotoRef.current);samplePhotoRef.current=url;setSamplePhoto(url);setNotice("샘플사진이 미리보기에 적용됐어요. 서버에는 저장되지 않습니다.");};
 const resetSamplePhoto=()=>{if(samplePhotoRef.current)URL.revokeObjectURL(samplePhotoRef.current);samplePhotoRef.current="";setSamplePhoto("");setNotice("기본 샘플사진으로 돌아왔어요.");};
 const auth=async()=>{const client=getSupabaseBrowserClient();const {data:{session}}=client?await client.auth.getSession():{data:{}};if(!session)throw new Error("로그인이 필요합니다.");return {Authorization:`Bearer ${session.access_token}`};};
 const load=async()=>{const response=await fetch("/api/admin/hero-presets",{headers:await auth()});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Hero 프리셋 목록을 불러오지 못했어요.");setState({loading:false,error:"",presets:result.presets||[]});};
 useEffect(()=>{load().catch((e)=>setState({loading:false,error:e.message,presets:[]}));},[]);
 const loadAssets=async(id)=>{const response=await fetch(`/api/admin/hero-presets/assets?heroPresetId=${encodeURIComponent(id)}`,{headers:await auth()});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Hero Asset을 불러오지 못했어요.");setAssets(result.assets||[]);};
 const open=(preset=null)=>{setEditing(preset?.id||"new");setAssets([]);if(preset?.id)loadAssets(preset.id).catch((e)=>setNotice(e.message));setForm(preset?{name:preset.name,preset_key:preset.preset_key,description:preset.description||"",status:preset.status,is_visible:preset.is_visible,sort_order:preset.sort_order,config:{...defaultConfig,...preset.config,display:{...defaultDisplay,...preset.config?.display},textLayers:Array.isArray(preset.config?.textLayers)?preset.config.textLayers.map((layer)=>({fontSize:32,color:"#ffffff",x:50,y:50,align:"center",...layer})):[]}}:{...empty,config:{...defaultConfig,display:{...defaultDisplay}}});setNotice("");};
 const setConfig=(key,value)=>setForm((current)=>({...current,config:{...current.config,[key]:value}}));
 const addTextLayer=()=>setForm((current)=>({...current,config:{...current.config,textLayers:[...(current.config.textLayers||[]),{id:`text-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,text:"",fontId:"great-vibes",fontSize:32,color:"#ffffff",x:50,y:50,align:"center"}]}}));
 const updateTextLayer=(id,key,value)=>setForm((current)=>({...current,config:{...current.config,textLayers:(current.config.textLayers||[]).map((layer)=>layer.id===id?{...layer,[key]:value}:layer)}}));
 const removeTextLayer=(id)=>setForm((current)=>({...current,config:{...current.config,textLayers:(current.config.textLayers||[]).filter((layer)=>layer.id!==id)}}));
 const uploadAsset=async(type,file)=>{if(!file||editing==="new"||assetBusy)return;setAssetBusy(type);setNotice("");try{const size=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(new Error("이미지 크기를 확인하지 못했어요."));image.src=URL.createObjectURL(file);});const data=new FormData();data.append("heroPresetId",editing);data.append("assetType",type);data.append("file",file);data.append("width",String(size.width));data.append("height",String(size.height));const response=await fetch("/api/admin/hero-presets/assets",{method:"POST",headers:await auth(),body:data});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Hero 이미지를 업로드하지 못했어요.");await loadAssets(editing);setNotice(type==="thumbnail"?"Hero 썸네일을 저장했습니다.":"Hero 프레임 이미지를 저장했습니다.");}catch(e){setNotice(e.message);}finally{setAssetBusy("");}};
 const activeFrame=assets.find((item)=>item.asset_type==="hero_frame"&&item.is_active)||null;
 const liveConfig={hero:{...form.config,frameAssetId:activeFrame?.id||null}};
 const liveAssets=activeFrame?.url?{[activeFrame.id]:activeFrame.url}:{};
 const liveInvitation={eventKind:"wedding",groom:"경원",bride:"보람",groomFatherName:"박영채",groomMotherName:"김이순",brideFatherName:"이규수",brideMotherName:"김덕임",date:"2026-10-17",time:"12:30",venue:"디어데이 웨딩홀",venueAddress:"서울특별시 중구 세종대로 110",message:"소중한 분들을 모시고 새로운 시작을 함께하려 합니다.",coverPhotoUrl:samplePhoto||"/templates/modern-001/preview.png"};
 const save=async(e)=>{e.preventDefault();if(saving)return;setSaving(true);setNotice("");try{const response=await fetch("/api/admin/hero-presets",{method:editing==="new"?"POST":"PATCH",headers:{...(await auth()),"Content-Type":"application/json"},body:JSON.stringify({...form,preset_key:form.preset_key.trim(),...(editing!=="new"?{id:editing}:{})})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"저장하지 못했어요.");await load();setEditing(null);setNotice("Hero 프리셋을 저장했습니다.");}catch(e){setNotice(e.message);}finally{setSaving(false);}};
 return <main style={{maxWidth:980,margin:"0 auto",padding:"32px 16px 64px"}}><p className="section-kicker">ADMIN · HERO PRESETS</p><h1>Hero 프레임 관리</h1><p>Hero는 사진·프레임·텍스트 배치만 관리합니다. 본문 배경과 장식은 기존 템플릿 관리에서 계속 관리합니다.</p><p><a href="/admin/templates">← 본문 테마 관리</a></p>
 {state.loading?<p>불러오는 중이에요.</p>:state.error?<p className="payment-error">{state.error}</p>:<>
 {!editing&&<button type="button" className="save-button" onClick={()=>open()}>새 Hero 프리셋</button>}{notice&&<p role="status">{notice}</p>}
 {editing?<form onSubmit={save} style={{...card,display:"grid",gap:14,marginTop:16}}><h2 style={{margin:0}}>{editing==="new"?"새 Hero 프리셋":"Hero 프리셋 수정"}</h2>
 <label style={field}>이름<input style={input} required maxLength={100} value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label>
 <label style={field}>Preset key<input style={input} required pattern="[a-z0-9](?:[a-z0-9]|_|-){2,79}" disabled={editing!=="new"} value={form.preset_key} onChange={(e)=>setForm({...form,preset_key:e.target.value.trim()})}/></label>
 <label style={field}>설명<textarea style={input} rows={3} maxLength={2000} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}>
 <label style={field}>상태<select style={input} value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="draft">제작중</option><option value="on_sale">사용중</option><option value="stopped">사용중지</option></select></label>
 <label style={field}>정렬순서<input style={input} type="number" min={-10000} max={10000} value={form.sort_order} onChange={(e)=>setForm({...form,sort_order:Number(e.target.value)})}/></label>
 <label style={{display:"flex",alignItems:"center",gap:7}}><input type="checkbox" checked={form.is_visible} onChange={(e)=>setForm({...form,is_visible:e.target.checked})}/> 사용자 선택에 노출</label></div>
 <section style={{border:"1px solid #eadfd8",borderRadius:10,padding:12,background:"#fff"}}><link rel="stylesheet" href={HERO_FONT_STYLESHEET}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><div><strong>Hero 폰트 라이브러리</strong><p style={{fontSize:12,color:"#806f66",margin:"5px 0 0"}}>한글·영문 웨딩용 12종의 실제 글씨를 미리 비교해 보세요.</p></div><button type="button" className="save-button" aria-expanded={fontLibraryOpen} onClick={()=>setFontLibraryOpen((v)=>!v)}>{fontLibraryOpen?"폰트 목록 닫기":"폰트 12종 보기"}</button></div>{fontLibraryOpen&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:9,marginTop:12}}>{HERO_FONTS.map((font)=><div key={font.id} style={{border:"1px solid #eadfd8",borderRadius:8,padding:12,minWidth:0}}><div style={{fontSize:12,color:"#806f66"}}>{font.category} · {font.name}</div><div lang={font.category.startsWith("한글")?"ko":"en"} style={{fontFamily:font.family,fontSize:font.category.includes("캘리그래피")?30:font.category.startsWith("영문")?24:19,lineHeight:1.5,marginTop:8,overflowWrap:"anywhere"}}>{font.sample}</div></div>)}</div>}<p style={{fontSize:11,color:"#806f66",margin:"10px 0 0"}}>현재 단계는 폰트 목록과 미리보기입니다. 다음 단계에서 텍스트 레이어별 폰트 선택을 연결합니다. 폰트 표시는 인터넷 연결이 필요합니다.</p></section>
 <section style={{border:"1px solid #eadfd8",borderRadius:10,padding:12,background:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"}}><div><strong>Hero 텍스트 레이어</strong><p style={{fontSize:12,color:"#806f66",margin:"5px 0 0"}}>최대 12개 · 문구 입력과 글씨체 선택 · 프리셋 저장</p></div><button type="button" className="save-button" disabled={(form.config.textLayers||[]).length>=12} onClick={addTextLayer}>+ 텍스트 추가</button></div>{!(form.config.textLayers||[]).length&&<p style={{fontSize:12,color:"#806f66"}}>추가된 텍스트가 없습니다. 위 버튼으로 문구를 추가하세요.</p>}{(form.config.textLayers||[]).map((layer,index)=><div key={layer.id} style={{border:"1px solid #eadfd8",borderRadius:8,padding:12,marginTop:10,display:"grid",gap:8}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong style={{fontSize:13}}>텍스트 {index+1}</strong><button type="button" className="save-button" onClick={()=>removeTextLayer(layer.id)}>삭제</button></div><label style={field}>문구<textarea style={input} rows={2} maxLength={200} value={layer.text} placeholder="Happy Wedding Day" onChange={(e)=>updateTextLayer(layer.id,"text",e.target.value)}/></label><label style={field}>폰트<select style={input} value={layer.fontId} onChange={(e)=>updateTextLayer(layer.id,"fontId",e.target.value)}>{HERO_FONTS.map((font)=><option key={font.id} value={font.id}>{font.category} · {font.name}</option>)}</select></label><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:8}}><label style={field}>글씨 크기 (px)<input style={input} type="number" min={8} max={100} step={1} value={layer.fontSize??32} onChange={(e)=>updateTextLayer(layer.id,"fontSize",Number(e.target.value))}/></label><label style={field}>글씨 색상<input style={input} type="color" value={layer.color||"#ffffff"} onChange={(e)=>updateTextLayer(layer.id,"color",e.target.value)}/></label><label style={field}>가로 위치 X (%)<input style={input} type="number" min={0} max={100} step={1} value={layer.x??50} onChange={(e)=>updateTextLayer(layer.id,"x",Number(e.target.value))}/></label><label style={field}>세로 위치 Y (%)<input style={input} type="number" min={0} max={100} step={1} value={layer.y??50} onChange={(e)=>updateTextLayer(layer.id,"y",Number(e.target.value))}/></label><label style={field}>정렬<select style={input} value={layer.align||"center"} onChange={(e)=>updateTextLayer(layer.id,"align",e.target.value)}><option value="left">왼쪽</option><option value="center">가운데</option><option value="right">오른쪽</option></select></label></div><div style={{fontFamily:HERO_FONTS.find((font)=>font.id===layer.fontId)?.family||"serif",fontSize:layer.fontSize??32,color:layer.color||"#ffffff",textAlign:layer.align||"center",lineHeight:1.5,overflowWrap:"anywhere",background:"#857b78",padding:12,borderRadius:7}}>{layer.text||"문구 미리보기"}</div></div>)}<p style={{fontSize:11,color:"#806f66",margin:"10px 0 0"}}>X·Y는 Hero 영역의 백분율입니다. 실제 사진 위 렌더링은 다음 단계에서 연결합니다.</p></section>
 <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(300px,390px)",gap:16,alignItems:"start"}}>
 <div><fieldset style={{border:"1px solid #eadfd8",borderRadius:10,padding:12}}><legend>Hero 레이아웃</legend><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:10}}>
 <label style={field}>표현 방식<select style={input} value={form.config.mode} onChange={(e)=>setConfig("mode",e.target.value)}><option value="photo">사진 중심형</option><option value="frame">컨셉 프레임형</option><option value="illustration">포스터/일러스트형</option></select></label>
 <label style={field}>비율<select style={input} value={form.config.aspectRatio} onChange={(e)=>setConfig("aspectRatio",e.target.value)}>{["4:5","1:1","3:4","16:9"].map(v=><option key={v}>{v}</option>)}</select></label>
 {[["positionX","사진 X 위치 %",0,100,1],["positionY","사진 Y 위치 %",0,100,1],["textYPercent","텍스트 Y 위치 %",0,100,1],["scheduleFontSize","날짜 글자 크기",8,24,1],["zoom","사진 Zoom",.5,2,.05],["overlayOpacity","Overlay 투명도",0,1,.05]].map(([key,label,min,max,step])=><label style={field} key={key}>{label}<input style={input} type="number" min={min} max={max} step={step} value={form.config[key]} onChange={(e)=>setConfig(key,Number(e.target.value))}/></label>)}
 <label style={field}>Overlay 색상<input style={input} type="color" value={form.config.overlayColor} onChange={(e)=>setConfig("overlayColor",e.target.value)}/></label>
 <label style={field}>상단 문구<input style={input} maxLength={60} value={form.config.mastheadText} onChange={(e)=>setConfig("mastheadText",e.target.value)}/></label>
 </div><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:12}}><label><input type="checkbox" checked={form.config.headerVisible} onChange={(e)=>setConfig("headerVisible",e.target.checked)}/> DearDay 표시</label><label><input type="checkbox" checked={form.config.mastheadVisible} onChange={(e)=>setConfig("mastheadVisible",e.target.checked)}/> 상단 행사문구 표시</label></div>
 <fieldset style={{marginTop:12,border:"1px solid #eadfd8",borderRadius:8}}><legend>Hero 표시 항목</legend><div style={{display:"flex",gap:12,flexWrap:"wrap"}}>{displayLabels.map(([key,label])=><label key={key}><input type="checkbox" checked={form.config.display[key]} onChange={(e)=>setConfig("display",{...form.config.display,[key]:e.target.checked})}/>{label}</label>)}</div></fieldset></fieldset></div>
 <aside style={{position:"sticky",top:16,border:"1px solid #eadfd8",borderRadius:12,padding:10,background:"#f8f3ef"}}><strong style={{display:"block",marginBottom:8}}>Hero LIVE PREVIEW</strong><p style={{fontSize:12,color:"#806f66",margin:"0 0 8px"}}>설정값이 저장 전에도 즉시 반영됩니다.</p><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap",marginBottom:10}}><label className="save-button" style={{cursor:"pointer",display:"inline-block",fontSize:12}}>샘플사진 업로드<input type="file" accept="image/jpeg,image/png,image/webp" style={{display:"none"}} onChange={(e)=>{const file=e.target.files?.[0];e.target.value="";changeSamplePhoto(file);}}/></label><button type="button" className="save-button" disabled={!samplePhoto} onClick={resetSamplePhoto} style={{fontSize:12}}>기본 사진으로</button></div><p style={{fontSize:11,color:"#806f66",margin:"0 0 8px"}}>선택한 사진은 이 브라우저의 미리보기에서만 사용되며, 저장·발행되는 Hero 이미지에는 영향을 주지 않습니다.</p><div ref={heroPreviewRef} className="hero-admin-live-preview" style={{width:"100%",overflow:"hidden",borderRadius:10,background:"#fff"}}><InvitationRenderer invitation={liveInvitation} eventKind="wedding" templateConfig={liveConfig} templateAssets={liveAssets}/><style>{`.hero-admin-live-preview .invitation-template > :not(.classic-masthead):not(.classic-hero){display:none!important}.hero-admin-live-preview .invitation-template{min-height:0!important}.hero-admin-live-preview .classic-hero{margin-bottom:0!important}`}</style></div></aside></div>
 {editing!=="new"&&<fieldset style={{border:"1px solid #eadfd8",borderRadius:10,padding:12}}><legend>Hero 썸네일 캡처</legend><p style={{marginTop:0,color:"#806f66",fontSize:13}}>LIVE PREVIEW를 캡처한 뒤 아래 영역을 클릭하고 Ctrl+V로 붙여넣으면 선택 화면 썸네일로 바로 업로드됩니다.</p><div tabIndex={0} onPaste={(e)=>{const item=[...e.clipboardData.items].find((entry)=>entry.type.startsWith("image/"));const blob=item?.getAsFile();if(!blob){setNotice("클립보드에 이미지가 없어요.");return;}e.preventDefault();const file=new File([blob],`${form.preset_key||"hero"}-thumbnail.${blob.type==="image/jpeg"?"jpg":"png"}`,{type:blob.type||"image/png"});uploadAsset("thumbnail",file);}} style={{border:"2px dashed #d7c5ba",borderRadius:10,padding:"18px 12px",textAlign:"center",cursor:"text",outline:"none",background:"#fff"}}><strong>여기를 클릭 → Ctrl+V</strong><div style={{fontSize:12,color:"#806f66",marginTop:5}}>클립보드 이미지 바로 업로드</div></div></fieldset>}
 {editing!=="new"&&<fieldset style={{border:"1px solid #eadfd8",borderRadius:10,padding:12}}><legend>Hero 이미지 Asset</legend><p style={{marginTop:0,color:"#806f66",fontSize:13}}>Hero 선택 화면용 썸네일과 실제 Hero 프레임을 각각 등록합니다. 새 파일을 올리면 기존 활성 이미지는 자동으로 교체됩니다.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}>{[["thumbnail","선택 화면 썸네일"],["hero_frame","실제 Hero 프레임"]].map(([type,label])=>{const asset=assets.find((item)=>item.asset_type===type&&item.is_active);return <div key={type} style={{border:"1px solid #eadfd8",borderRadius:10,padding:10}}><strong>{label}</strong>{asset?.url?<img src={asset.url} alt="" style={{display:"block",width:"100%",maxHeight:220,objectFit:"contain",margin:"10px 0",borderRadius:8,background:"#f7f3f0"}}/>:<p style={{fontSize:12,color:"#8d7a70"}}>등록된 이미지 없음</p>}<label className="save-button" style={{display:"inline-block",cursor:assetBusy?"wait":"pointer"}}>{assetBusy===type?"업로드 중...":asset?"교체 업로드":"이미지 업로드"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={!!assetBusy} style={{display:"none"}} onChange={(e)=>{const file=e.target.files?.[0];e.target.value="";if(file)uploadAsset(type,file);}}/></label></div>})}</div></fieldset>}
 {editing==="new"&&<p style={{margin:0,color:"#806f66",fontSize:13}}>기본정보를 먼저 저장한 뒤 썸네일과 Hero 프레임 이미지를 등록할 수 있습니다.</p>}
 <div style={{display:"flex",gap:8}}><button className="save-button" disabled={saving}>{saving?"저장 중...":"저장"}</button><button type="button" className="save-button" disabled={saving} onClick={()=>setEditing(null)}>취소</button></div></form>:
 <div style={{display:"grid",gap:12,marginTop:16}}>{state.presets.length?state.presets.map((preset)=><article key={preset.id} style={card}><h2 style={{margin:"0 0 8px"}}>{preset.name}</h2><p style={{margin:"4px 0"}}>{preset.preset_key} · {preset.status==="on_sale"?"사용중":preset.status==="stopped"?"사용중지":"제작중"} · {preset.is_visible?"노출":"숨김"}</p><button type="button" className="save-button" onClick={()=>open(preset)}>수정하기</button></article>):<p>등록된 Hero 프리셋이 없습니다.</p>}</div>}</>}</main>;
}
