"use client";
import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "../../../lib/supabase/browser";
import AdminDesignNav from "../admin-design-nav";
import CompletedTemplatePreview from "./completed-template-preview";

const emptySample={child_name:"",child_last_name:"",child_first_name:"",birth_date:"",parent1_name:"",parent2_name:"",groom_name:"",groom_last_name:"",groom_first_name:"",bride_name:"",bride_last_name:"",bride_first_name:"",groom_father_name:"",groom_mother_name:"",bride_father_name:"",bride_mother_name:"",event_date:"",event_time:"",venue:"",venue_address:"",venue_building:"",venue_detail:"",groom_bank:"",groom_account:"",groom_account_holder:"",bride_bank:"",bride_account:"",bride_account_holder:"",invitation_message:"",gallery_images:[],timeline_enabled:false,timeline_items:[]};
const blank={name:"",template_key:"",category:"wedding",hero_preset_id:"",body_template_id:"",price:0,description:"",thumbnail_url:"",thumbnail_1_url:"",thumbnail_2_url:"",sample_content:emptySample,is_visible:false,is_featured:false,sort_order:0};
const categoryToEventKind=(category)=>category==="first-birthday"?"first_birthday":category||"wedding";
const box={border:"1px solid #e5ddd8",borderRadius:14,padding:16,background:"#fff"};
const input={width:"100%",boxSizing:"border-box",padding:"10px 12px",border:"1px solid #d8ccc5",borderRadius:8,background:"#fff"};
const primaryButton={border:0,borderRadius:9,padding:"10px 16px",background:"#23439a",color:"#fff",fontWeight:700,cursor:"pointer"};
const secondaryButton={border:"1px solid #23439a",borderRadius:9,padding:"9px 15px",background:"#fff",color:"#23439a",fontWeight:700,cursor:"pointer"};
export default function CompletedTemplatesPage(){
 const [data,setData]=useState({items:[],heroes:[],bodies:[]}),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[notice,setNotice]=useState(""),[uploading,setUploading]=useState(0),[sampleUploading,setSampleUploading]=useState(""),[sharedTimelineUploading,setSharedTimelineUploading]=useState(""),[sharedSample,setSharedSample]=useState(emptySample),[sharedSaving,setSharedSaving]=useState(false),[sharedPlaces,setSharedPlaces]=useState([]),[sharedPlaceSearching,setSharedPlaceSearching]=useState(false);
 const auth=async()=>{const c=getSupabaseBrowserClient();const {data:{session}}=await c.auth.getSession();if(!session)throw new Error("다시 로그인해 주세요.");return {Authorization:`Bearer ${session.access_token}`};};
 const load=async()=>{const headers=await auth();const r=await fetch("/api/admin/completed-templates",{headers});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);};
 useEffect(()=>{load().catch(e=>setNotice(e.message));},[]);
 useEffect(()=>{let active=true;(async()=>{try{const headers=await auth();const kind=categoryToEventKind(form.category);const r=await fetch(`/api/admin/completed-template-sample-defaults?eventKind=${encodeURIComponent(kind)}`,{headers});const j=await r.json();if(active&&r.ok)setSharedSample({...emptySample,...(j.sample_content||{})});}catch(e){if(active)setNotice(e.message);}})();return()=>{active=false;};},[form.category]);
 const hero=useMemo(()=>data.heroes.find(x=>x.id===form.hero_preset_id),[data,form.hero_preset_id]);
 const body=useMemo(()=>data.bodies.find(x=>x.id===form.body_template_id),[data,form.body_template_id]);
 const save=async(e)=>{e.preventDefault();setNotice("");try{const r=await fetch("/api/admin/completed-templates",{method:editing?"PATCH":"POST",headers:{...(await auth()),"Content-Type":"application/json"},body:JSON.stringify({...form,...(editing?{id:editing}:{})})});const j=await r.json();if(!r.ok)throw new Error(j.error);setForm(blank);setEditing(null);await load();setNotice("저장했습니다.");}catch(e){setNotice(e.message);}};
 const edit=x=>{setEditing(x.id);const own=x.sample_content||{},hasOwn=Object.values(own).some(v=>Array.isArray(v)?v.length:Boolean(v));setForm({name:x.name,template_key:x.template_key,category:x.category,hero_preset_id:x.hero_preset_id,body_template_id:x.body_template_id,price:x.price,description:x.description||"",thumbnail_url:x.thumbnail_url||"",thumbnail_1_url:x.thumbnail_1_url||"",thumbnail_2_url:x.thumbnail_2_url||"",sample_content:{...emptySample,...(hasOwn?own:sharedSample)},is_visible:x.is_visible,is_featured:Boolean(x.is_featured),sort_order:x.sort_order});window.scrollTo({top:0,behavior:"smooth"});};
 const uploadThumbnail=async(slot,file)=>{if(!editing){setNotice("완성 템플릿을 먼저 저장한 뒤 대표 이미지를 업로드해 주세요.");return;}if(!file)return;setUploading(slot);setNotice("");try{const fd=new FormData();fd.append("completedTemplateId",editing);fd.append("slot",String(slot));fd.append("file",file);const r=await fetch("/api/admin/completed-templates/thumbnails",{method:"POST",headers:await auth(),body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);setForm(v=>({...v,[slot===1?"thumbnail_1_url":"thumbnail_2_url"]:j.url}));await load();setNotice(`대표 이미지 ${slot}을 저장했습니다.`);}catch(e){setNotice(e.message);}finally{setUploading(0);}};
 const setShared=(key,value)=>setSharedSample(v=>({...emptySample,...v,[key]:value}));
 const saveShared=async()=>{setSharedSaving(true);setNotice("");try{const r=await fetch("/api/admin/completed-template-sample-defaults",{method:"PUT",headers:{...(await auth()),"Content-Type":"application/json"},body:JSON.stringify({event_kind:categoryToEventKind(form.category),sample_content:sharedSample})});const j=await r.json();if(!r.ok)throw new Error(j.error);setSharedSample({...emptySample,...(j.sample_content||{})});setNotice("행사유형별 샘플 콘텐츠를 저장했습니다.");}catch(e){setNotice(e.message);}finally{setSharedSaving(false);}};
 const updateSharedTimeline=(index,key,value)=>setSharedSample(v=>({...v,timeline_items:(Array.isArray(v.timeline_items)?v.timeline_items:[]).map((item,i)=>i===index?{...item,[key]:value}:item)}));
 const addSharedTimeline=()=>setSharedSample(v=>({...v,timeline_enabled:true,timeline_items:[...(Array.isArray(v.timeline_items)?v.timeline_items:[]),{id:`sample-${Date.now()}`,date:"",text:"",photoUrl:""}].slice(0,6)}));
 const removeSharedTimeline=index=>setSharedSample(v=>({...v,timeline_items:(Array.isArray(v.timeline_items)?v.timeline_items:[]).filter((_,i)=>i!==index)}));
 const uploadSharedTimelinePhoto=async(index,file)=>{if(!file)return;setSharedTimelineUploading(String(index));setNotice("");try{const fd=new FormData();fd.append("eventKind",categoryToEventKind(form.category));fd.append("file",file);const r=await fetch("/api/admin/completed-template-sample-defaults/images",{method:"POST",headers:await auth(),body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);updateSharedTimeline(index,"photoUrl",j.url);setNotice("성장 기록 샘플 사진을 업로드했습니다. 공통 샘플 저장을 눌러 확정해 주세요.");}catch(e){setNotice(e.message);}finally{setSharedTimelineUploading("");}};
 const updateSampleTimeline=(index,key,value)=>setForm(v=>({...v,sample_content:{...emptySample,...(v.sample_content||{}),timeline_items:(Array.isArray(v.sample_content?.timeline_items)?v.sample_content.timeline_items:[]).map((item,i)=>i===index?{...item,[key]:value}:item)}}));
 const addSampleTimeline=()=>setForm(v=>({...v,sample_content:{...emptySample,...(v.sample_content||{}),timeline_enabled:true,timeline_items:[...(Array.isArray(v.sample_content?.timeline_items)?v.sample_content.timeline_items:[]),{id:`sample-${Date.now()}`,date:"",text:"",photoUrl:""}].slice(0,6)}}));
 const removeSampleTimeline=index=>setForm(v=>({...v,sample_content:{...emptySample,...(v.sample_content||{}),timeline_items:(Array.isArray(v.sample_content?.timeline_items)?v.sample_content.timeline_items:[]).filter((_,i)=>i!==index)}}));
 const uploadSampleTimelinePhoto=async(index,file)=>{if(!editing){setNotice("완성 템플릿을 먼저 저장한 뒤 성장 기록 사진을 업로드해 주세요.");return;}if(!file)return;const item=form.sample_content?.timeline_items?.[index];if(!item?.id)return;setSampleUploading(`timeline-${index}`);setNotice("");try{const fd=new FormData();fd.append("completedTemplateId",editing);fd.append("kind","timeline");fd.append("timelineId",item.id);fd.append("file",file);fd.append("sampleContent",JSON.stringify(form.sample_content||{}));const r=await fetch("/api/admin/completed-templates/sample-images",{method:"POST",headers:await auth(),body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);setForm(v=>({...v,sample_content:{...emptySample,...(j.sample_content||v.sample_content||{})}}));setNotice("성장 기록 사진을 업로드했습니다.");}catch(e){setNotice(e.message);}finally{setSampleUploading("");}};
 const searchSharedPlaces=async()=>{const q=(sharedSample.venue||"").trim();if(!q){setNotice("장소명을 먼저 입력해 주세요.");return;}setSharedPlaceSearching(true);setNotice("");try{const r=await fetch(`/api/places?q=${encodeURIComponent(q)}`);const j=await r.json();if(!r.ok)throw new Error(j.error||"장소 검색에 실패했습니다.");setSharedPlaces(j.items||[]);}catch(e){setNotice(e.message);}finally{setSharedPlaceSearching(false);}};
 const selectSharedPlace=place=>{setSharedSample(v=>({...v,venue:String(place.title||"").replace(/<[^>]+>/g,""),venue_address:place.roadAddress||place.address||"",venue_building:""}));setSharedPlaces([]);};
 const setSample=(key,value)=>setForm(v=>({...v,sample_content:{...emptySample,...(v.sample_content||{}),[key]:value}}));
  const setSharedNamePart=(side,part,value)=>setSharedSample(v=>{const lastKey=`${side}_last_name`,firstKey=`${side}_first_name`,nameKey=`${side}_name`,next={...v,[part==="last"?lastKey:firstKey]:value};next[nameKey]=`${next[lastKey]||""}${next[firstKey]||""}`.trim();return next;});
  const setSampleNamePart=(side,part,value)=>setForm(v=>{const current={...emptySample,...(v.sample_content||{})},lastKey=`${side}_last_name`,firstKey=`${side}_first_name`,nameKey=`${side}_name`;current[part==="last"?lastKey:firstKey]=value;current[nameKey]=`${current[lastKey]||""}${current[firstKey]||""}`.trim();return {...v,sample_content:current};});
 const removeSampleImage=async(url)=>{if(!editing)return;setSampleUploading("gallery");setNotice("");try{const r=await fetch("/api/admin/completed-templates/sample-images",{method:"DELETE",headers:{...(await auth()),"Content-Type":"application/json"},body:JSON.stringify({completedTemplateId:editing,url})});const j=await r.json();if(!r.ok)throw new Error(j.error);setForm(v=>({...v,sample_content:{...emptySample,...(v.sample_content||{}),gallery_images:(v.sample_content?.gallery_images||[]).filter(x=>x!==url)}}));setNotice("갤러리 샘플 사진을 삭제했습니다.");}catch(e){setNotice(e.message);}finally{setSampleUploading("");}};
 const uploadSampleImages=async(files)=>{if(!editing){setNotice("완성 템플릿을 먼저 저장한 뒤 샘플 이미지를 업로드해 주세요.");return;}const list=Array.from(files||[]).slice(0,Math.max(0,20-(form.sample_content?.gallery_images||[]).length));if(!list.length)return;setSampleUploading("gallery");setNotice("");try{let current={...emptySample,...(form.sample_content||{})};for(const file of list){const fd=new FormData();fd.append("completedTemplateId",editing);fd.append("kind","gallery");fd.append("file",file);fd.append("sampleContent",JSON.stringify(current));const r=await fetch("/api/admin/completed-templates/sample-images",{method:"POST",headers:await auth(),body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);current={...current,...(j.sample_content||{})};setForm(v=>({...v,sample_content:{...current}}));}setNotice(`${list.length}장의 갤러리 샘플 사진을 추가했습니다.`);}catch(e){setNotice(e.message);}finally{setSampleUploading("");}};
 return <main style={{maxWidth:1100,margin:"32px auto",padding:"0 20px",fontFamily:"sans-serif"}}>
  <h1>완성 템플릿 관리</h1><AdminDesignNav current="completed"/><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"0 0 14px"}}><button type="button" style={secondaryButton} onClick={()=>document.getElementById("completed-template-list")?.scrollIntoView({behavior:"smooth",block:"start"})}>← 목록 보기</button><button type="submit" form="completed-template-form" style={primaryButton}>{editing?"수정 저장":"완성 템플릿 저장"}</button>{editing&&<button type="button" style={secondaryButton} onClick={()=>{setEditing(null);setForm(blank);}}>취소</button>}</div><p style={{color:"#766"}}>Hero 프리셋과 본문 테마를 조합해 사용자에게 보여줄 완성 템플릿을 만듭니다. 디자인 세부값은 여기서 수정하지 않습니다.</p>
  <section style={{...box,display:"grid",gap:12,marginBottom:16,background:"#f8fbff"}}>
   <div><h2 style={{margin:"0 0 4px"}}>공통 샘플 콘텐츠</h2><small style={{color:"#667"}}>새 완성 템플릿에서 기본으로 사용할 예시 정보입니다. 한 번 저장해 두고 공통으로 사용합니다.</small></div>
   <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12}}>{(form.category==="first-birthday"?[["child_last_name","아이 성"],["child_first_name","아이 이름"],["parent1_name","아빠 이름"],["parent2_name","엄마 이름"],["birth_date","생년월일"]]:[["groom_last_name","신랑 성"],["groom_first_name","신랑 이름"],["bride_last_name","신부 성"],["bride_first_name","신부 이름"],["groom_father_name","신랑 아버지"],["groom_mother_name","신랑 어머니"],["bride_father_name","신부 아버지"],["bride_mother_name","신부 어머니"]]).map(([key,label])=><label key={key}>{label}<input style={input} value={sharedSample[key]||((key==="groom_first_name"&&!sharedSample.groom_last_name&&!sharedSample.groom_first_name)?sharedSample.groom_name:(key==="bride_first_name"&&!sharedSample.bride_last_name&&!sharedSample.bride_first_name)?sharedSample.bride_name:"")} onChange={e=>key.startsWith("child_")&&(key.endsWith("last_name")||key.endsWith("first_name"))?setSharedNamePart("child",key.endsWith("last_name")?"last":"first",e.target.value):key.startsWith("groom_")&&(key.endsWith("last_name")||key.endsWith("first_name"))?setSharedNamePart("groom",key.endsWith("last_name")?"last":"first",e.target.value):key.startsWith("bride_")&&(key.endsWith("last_name")||key.endsWith("first_name"))?setSharedNamePart("bride",key.endsWith("last_name")?"last":"first",e.target.value):setShared(key,e.target.value)}/></label>)}<label>행사 날짜<input type="date" style={input} value={sharedSample.event_date||""} onChange={e=>setShared("event_date",e.target.value)}/></label><label>행사 시간<input style={input} placeholder="예: 오후 2시" value={sharedSample.event_time||""} onChange={e=>setShared("event_time",e.target.value)}/></label></div>
   {form.category==="first-birthday"&&<div style={{...box,display:"grid",gap:10,background:"#fffaf5"}}><label><input type="checkbox" checked={sharedSample.timeline_enabled===true} onChange={e=>setShared("timeline_enabled",e.target.checked)}/> 성장 기록 샘플 사용</label>{sharedSample.timeline_enabled===true&&<>{(Array.isArray(sharedSample.timeline_items)?sharedSample.timeline_items:[]).map((item,index)=><div key={item.id||index} style={{display:"grid",gridTemplateColumns:"140px 1fr 220px auto",gap:8,alignItems:"end"}}><label>날짜<input type="date" style={input} value={item.date||""} onChange={e=>updateSharedTimeline(index,"date",e.target.value)}/></label><label>한 줄 문구<input style={input} maxLength={80} value={item.text||""} onChange={e=>updateSharedTimeline(index,"text",e.target.value)}/></label><label>사진{item.photoUrl&&<img src={item.photoUrl} alt="" style={{display:"block",width:64,height:64,objectFit:"cover",borderRadius:7,margin:"4px 0"}}/>}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={sharedTimelineUploading===String(index)} onChange={e=>{const file=e.target.files?.[0];e.target.value="";void uploadSharedTimelinePhoto(index,file);}}/></label><button type="button" style={secondaryButton} onClick={()=>removeSharedTimeline(index)}>삭제</button></div>)}{(sharedSample.timeline_items||[]).length<6&&<button type="button" style={secondaryButton} onClick={addSharedTimeline}>+ 성장 기록 추가</button>}</>}</div>}
   <div style={{display:"grid",gap:8}}><label>장소명<div style={{display:"flex",gap:8}}><input style={input} value={sharedSample.venue||""} onChange={e=>setShared("venue",e.target.value)} onKeyDown={e=>e.key==="Enter"&&(e.preventDefault(),searchSharedPlaces())}/><button type="button" style={secondaryButton} onClick={searchSharedPlaces}>{sharedPlaceSearching?"검색 중":"장소 검색"}</button></div></label>{sharedPlaces.length>0&&<div style={{...box,padding:8}}>{sharedPlaces.map(place=><button key={[place.mapx,place.mapy,place.title].join("-")} type="button" onClick={()=>selectSharedPlace(place)} style={{display:"block",width:"100%",textAlign:"left",padding:8,border:0,borderBottom:"1px solid #eee",background:"#fff",cursor:"pointer"}}><b>{String(place.title||"").replace(/<[^>]+>/g,"")}</b><div style={{fontSize:12,color:"#667"}}>{place.roadAddress||place.address}</div></button>)}</div>}<label>기본주소<input style={input} value={sharedSample.venue_address||""} onChange={e=>setShared("venue_address",e.target.value)}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><label>건물명<input style={input} value={sharedSample.venue_building||""} onChange={e=>setShared("venue_building",e.target.value)}/></label><label>상세주소<input style={input} value={sharedSample.venue_detail||""} onChange={e=>setShared("venue_detail",e.target.value)}/></label></div><small style={{color:"#667"}}>전체 미리보기에서는 기본주소를 이용해 기존 지도 컴포넌트에 표시합니다.</small></div>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{[["groom","신랑측"],["bride","신부측"]].map(([side,label])=><div key={side} style={{...box,padding:12}}><b>{label} 샘플 계좌</b><label>은행<input style={input} value={sharedSample[`${side}_bank`]||""} onChange={e=>setShared(`${side}_bank`,e.target.value)}/></label><label>계좌번호<input style={input} value={sharedSample[`${side}_account`]||""} onChange={e=>setShared(`${side}_account`,e.target.value)}/></label><label>예금주<input style={input} value={sharedSample[`${side}_account_holder`]||""} onChange={e=>setShared(`${side}_account_holder`,e.target.value)}/></label></div>)}</div>
   <label>초대 문구<textarea style={{...input,minHeight:90}} value={sharedSample.invitation_message||""} onChange={e=>setShared("invitation_message",e.target.value)}/></label>
   <div style={{display:"flex",justifyContent:"flex-end"}}><button type="button" style={primaryButton} disabled={sharedSaving} onClick={saveShared}>{sharedSaving?"저장 중...":"공통 샘플 저장"}</button></div>
  </section>
  <form id="completed-template-form" onSubmit={save} style={{...box,display:"grid",gap:12}}>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><label>템플릿명<input style={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Template key<input style={input} value={form.template_key} disabled={!!editing} onChange={e=>setForm({...form,template_key:e.target.value})}/></label></div>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><label>Hero<select style={input} value={form.hero_preset_id} onChange={e=>setForm({...form,hero_preset_id:e.target.value})}><option value="">선택</option>{data.heroes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>본문 테마<select style={input} value={form.body_template_id} onChange={e=>setForm({...form,body_template_id:e.target.value})}><option value="">선택</option>{data.bodies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>
   {(hero||body)&&<div style={{padding:12,borderRadius:10,background:"#faf7f5"}}><b>조합 확인</b><div>Hero: {hero?.name||"-"} + 본문 테마: {body?.name||"-"}</div></div>}<section style={{...box,background:"#faf7f5"}}><CompletedTemplatePreview heroPresetId={form.hero_preset_id} bodyTemplateId={form.body_template_id} sampleContent={form.sample_content} category={form.category}/></section>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:12}}><label>카테고리<select style={input} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{[["wedding","결혼식"],["first-birthday","돌잔치"],["birthday","생일"],["gathering","모임·동창회"],["party","파티"],["custom","직접 만들기"]].map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>가격<input style={input} type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>정렬<input style={input} type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label></div>
   <label>설명<textarea style={{...input,minHeight:70}} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
   <section style={{...box,background:"#f8fbff",display:"grid",gap:12}}>
    <div><h2 style={{margin:"0 0 4px"}}>샘플 콘텐츠 관리</h2><small style={{color:"#667"}}>공통 샘플 콘텐츠를 기본으로 사용합니다. 필요한 템플릿만 여기서 내용을 바꿔 저장할 수 있습니다.</small></div>
    <button type="button" style={secondaryButton} onClick={()=>setForm(v=>({...v,sample_content:{...emptySample,...sharedSample,gallery_images:(v.sample_content?.gallery_images||[]).length?v.sample_content.gallery_images:(sharedSample.gallery_images||[])}}))}>공통 샘플 콘텐츠 불러오기</button>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{(form.category==="first-birthday"?[["child_last_name","아이 성"],["child_first_name","아이 이름"],["parent1_name","아빠 이름"],["parent2_name","엄마 이름"],["birth_date","생년월일"]]:[["groom_last_name","신랑 성"],["groom_first_name","신랑 이름"],["bride_last_name","신부 성"],["bride_first_name","신부 이름"],["groom_father_name","신랑 아버지"],["groom_mother_name","신랑 어머니"],["bride_father_name","신부 아버지"],["bride_mother_name","신부 어머니"]]).map(([key,label])=><label key={key}>{label}<input style={input} value={form.sample_content?.[key]||((key==="groom_first_name"&&!form.sample_content?.groom_last_name&&!form.sample_content?.groom_first_name)?form.sample_content?.groom_name:(key==="bride_first_name"&&!form.sample_content?.bride_last_name&&!form.sample_content?.bride_first_name)?form.sample_content?.bride_name:"")} onChange={e=>key.startsWith("child_")&&(key.endsWith("last_name")||key.endsWith("first_name"))?setSampleNamePart("child",key.endsWith("last_name")?"last":"first",e.target.value):key.startsWith("groom_")&&(key.endsWith("last_name")||key.endsWith("first_name"))?setSampleNamePart("groom",key.endsWith("last_name")?"last":"first",e.target.value):key.startsWith("bride_")&&(key.endsWith("last_name")||key.endsWith("first_name"))?setSampleNamePart("bride",key.endsWith("last_name")?"last":"first",e.target.value):setSample(key,e.target.value)}/></label>)}<label>행사 날짜<input style={input} type="date" value={form.sample_content?.event_date||""} onChange={e=>setSample("event_date",e.target.value)}/></label><label>행사 시간<input style={input} placeholder="예: 오후 2시" value={form.sample_content?.event_time||""} onChange={e=>setSample("event_time",e.target.value)}/></label></div>
    {form.category==="first-birthday"&&<div style={{...box,display:"grid",gap:10,background:"#fffaf5"}}><label><input type="checkbox" checked={form.sample_content?.timeline_enabled===true} onChange={e=>setSample("timeline_enabled",e.target.checked)}/> 성장 기록 샘플 사용</label>{form.sample_content?.timeline_enabled===true&&<>{(Array.isArray(form.sample_content?.timeline_items)?form.sample_content.timeline_items:[]).map((item,index)=><div key={item.id||index} style={{display:"grid",gridTemplateColumns:"140px 1fr 220px auto",gap:8,alignItems:"end"}}><label>날짜<input type="date" style={input} value={item.date||""} onChange={e=>updateSampleTimeline(index,"date",e.target.value)}/></label><label>한 줄 문구<input style={input} maxLength={80} value={item.text||""} onChange={e=>updateSampleTimeline(index,"text",e.target.value)}/></label><label>사진{item.photoUrl&&<img src={item.photoUrl} alt="" style={{display:"block",width:64,height:64,objectFit:"cover",borderRadius:7,margin:"4px 0"}}/>}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={!editing||sampleUploading===`timeline-${index}`} onChange={e=>{const file=e.target.files?.[0];e.target.value="";void uploadSampleTimelinePhoto(index,file);}}/></label><button type="button" style={secondaryButton} onClick={()=>removeSampleTimeline(index)}>삭제</button></div>)}{(form.sample_content?.timeline_items||[]).length<6&&<button type="button" style={secondaryButton} onClick={addSampleTimeline}>+ 성장 기록 추가</button>}</>}</div>}\n    <label>장소<input style={input} value={form.sample_content?.venue||""} onChange={e=>setSample("venue",e.target.value)}/></label><label>기본주소<input style={input} value={form.sample_content?.venue_address||""} onChange={e=>setSample("venue_address",e.target.value)}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><label>건물명<input style={input} value={form.sample_content?.venue_building||""} onChange={e=>setSample("venue_building",e.target.value)}/></label><label>상세주소<input style={input} value={form.sample_content?.venue_detail||""} onChange={e=>setSample("venue_detail",e.target.value)}/></label></div><label>초대 문구<textarea style={{...input,minHeight:90}} value={form.sample_content?.invitation_message||""} onChange={e=>setSample("invitation_message",e.target.value)}/></label>
    <div style={{padding:12,border:"1px solid #dfeafb",borderRadius:10,background:"#fff"}}><b>갤러리 샘플 사진</b><div style={{fontSize:12,color:"#667",margin:"4px 0 8px"}}>공통 갤러리를 기본으로 사용하고, 필요한 템플릿만 개별 갤러리로 바꿀 수 있습니다.</div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:8}}>{(form.sample_content?.gallery_images||[]).map((url,i)=><span key={url+i} style={{position:"relative",display:"inline-block"}}><img src={url} alt={`갤러리 ${i+1}`} style={{width:64,height:64,objectFit:"cover",borderRadius:7}}/><button type="button" aria-label={`갤러리 ${i+1} 삭제`} onClick={()=>removeSampleImage(url)} disabled={!!sampleUploading} style={{position:"absolute",right:-5,top:-5,width:20,height:20,borderRadius:"50%",border:"1px solid #bbb",background:"#fff",cursor:"pointer",lineHeight:"16px"}}>×</button></span>)}</div><input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={!editing||!!sampleUploading||(form.sample_content?.gallery_images||[]).length>=20} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value="";void uploadSampleImages(files);}}/>{sampleUploading==="gallery"&&<small> 업로드 중...</small>}</div>
   </section>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
    {[1,2].map(slot=>{const url=form[slot===1?"thumbnail_1_url":"thumbnail_2_url"],disabled=!editing||uploading!==0;const paste=e=>{if(disabled)return;const file=[...e.clipboardData.items].find(item=>item.type.startsWith("image/"))?.getAsFile();if(file){e.preventDefault();void uploadThumbnail(slot,file);}};return <div key={slot} style={{padding:12,border:"1px solid #e5ddd8",borderRadius:10}}><b>대표 이미지 {slot}</b><div tabIndex={disabled?-1:0} onPaste={paste} style={{margin:"8px 0 10px",padding:"18px 12px",border:"1px dashed #9ebcf4",borderRadius:9,background:disabled?"#f5f5f5":"#f5f9ff",textAlign:"center",outline:"none",cursor:disabled?"default":"text"}}><strong>{editing?"여기를 클릭 → Ctrl+V":"완성 템플릿을 먼저 저장해 주세요"}</strong><div style={{fontSize:12,color:"#667",marginTop:5}}>{editing?"클립보드 이미지 바로 업로드":"저장 후 캡처 이미지를 붙여넣을 수 있어요"}</div></div>{url&&<img src={url} alt={`대표 이미지 ${slot}`} style={{display:"block",width:"100%",maxWidth:220,height:150,objectFit:"cover",borderRadius:8,marginBottom:10}}/>}<div style={{fontSize:12,color:"#766",marginBottom:6}}>또는 파일 선택 · JPG, PNG, WebP · 15MB 이하</div><input type="file" accept="image/jpeg,image/png,image/webp" disabled={disabled} onChange={e=>{const file=e.target.files?.[0];e.target.value="";void uploadThumbnail(slot,file);}}/>{uploading===slot&&<small> 업로드 중...</small>}</div>;})}
   </div>
   <div style={{display:"flex",gap:18,alignItems:"center",flexWrap:"wrap"}}><label><input type="checkbox" checked={form.is_visible} onChange={e=>setForm({...form,is_visible:e.target.checked})}/> 컬렉션 노출</label><label><input type="checkbox" checked={form.is_featured} onChange={e=>setForm({...form,is_featured:e.target.checked})}/> 인기 템플릿 미리보기</label></div>
  </form>
  {notice&&<p>{notice}</p>}
  <h2 id="completed-template-list" style={{marginTop:30,scrollMarginTop:20}}>저장된 완성 템플릿</h2>
  <div style={{display:"grid",gap:10}}>{data.items.map(x=><div key={x.id} style={{...box,display:"flex",justifyContent:"space-between",gap:16,alignItems:"center"}}><div><b>{x.name}</b><div style={{fontSize:13,color:"#766"}}>{data.heroes.find(h=>h.id===x.hero_preset_id)?.name||"Hero"} + {data.bodies.find(b=>b.id===x.body_template_id)?.name||"본문 테마"} · {x.price.toLocaleString()}원 · {x.is_visible?"노출":"숨김"}</div></div><button onClick={()=>edit(x)}>수정</button></div>)}</div>
 </main>;
}
