// Curated, reusable font catalog for Hero text layers.
// Google Fonts are loaded only where the editor or renderer needs them.
export const HERO_FONTS = [
  { id: "noto-serif-kr", name: "Noto Serif KR", category: "한글 명조", family: '"Noto Serif KR", serif', sample: "우리의 소중한 순간" },
  { id: "nanum-myeongjo", name: "Nanum Myeongjo", category: "한글 명조", family: '"Nanum Myeongjo", serif', sample: "우리의 소중한 순간" },
  { id: "gowun-batang", name: "Gowun Batang", category: "한글 감성", family: '"Gowun Batang", serif', sample: "우리의 소중한 순간" },
  { id: "gowun-dodum", name: "Gowun Dodum", category: "한글 고딕", family: '"Gowun Dodum", sans-serif', sample: "우리의 소중한 순간" },
  { id: "noto-sans-kr", name: "Noto Sans KR", category: "한글 고딕", family: '"Noto Sans KR", sans-serif', sample: "우리의 소중한 순간" },
  { id: "playfair-display", name: "Playfair Display", category: "영문 세리프", family: '"Playfair Display", serif', sample: "Our Wedding Day" },
  { id: "cormorant-garamond", name: "Cormorant Garamond", category: "영문 세리프", family: '"Cormorant Garamond", serif', sample: "Our Wedding Day" },
  { id: "great-vibes", name: "Great Vibes", category: "영문 캘리그래피", family: '"Great Vibes", cursive', sample: "Happy Wedding Day" },
  { id: "allura", name: "Allura", category: "영문 캘리그래피", family: '"Allura", cursive', sample: "Happy Wedding Day" },
  { id: "alex-brush", name: "Alex Brush", category: "영문 캘리그래피", family: '"Alex Brush", cursive', sample: "Happy Wedding Day" },
  { id: "parisienne", name: "Parisienne", category: "영문 캘리그래피", family: '"Parisienne", cursive', sample: "Happy Wedding Day" },
  { id: "dancing-script", name: "Dancing Script", category: "영문 손글씨", family: '"Dancing Script", cursive', sample: "Happy Wedding Day" },
  { id: "hahmlet", name: "Hahmlet", category: "한글 명조", family: '"Hahmlet", serif', sample: "우리의 소중한 순간" },
  { id: "song-myung", name: "Song Myung", category: "한글 명조", family: '"Song Myung", serif', sample: "우리의 소중한 순간" },
  { id: "nanum-pen-script", name: "Nanum Pen Script", category: "한글 손글씨", family: '"Nanum Pen Script", cursive', sample: "우리의 소중한 순간" },
  { id: "nanum-brush-script", name: "Nanum Brush Script", category: "한글 손글씨", family: '"Nanum Brush Script", cursive', sample: "우리의 소중한 순간" },
  { id: "gaegu", name: "Gaegu", category: "한글 손글씨", family: '"Gaegu", cursive', sample: "우리의 소중한 순간" },
  { id: "hi-melody", name: "Hi Melody", category: "한글 손글씨", family: '"Hi Melody", cursive', sample: "우리의 소중한 순간" },
  { id: "ibm-plex-sans-kr", name: "IBM Plex Sans KR", category: "한글 고딕", family: '"IBM Plex Sans KR", sans-serif', sample: "우리의 소중한 순간" },
  { id: "cinzel", name: "Cinzel", category: "영문 세리프", family: '"Cinzel", serif', sample: "Our Wedding Day" },
  { id: "bodoni-moda", name: "Bodoni Moda", category: "영문 세리프", family: '"Bodoni Moda", serif', sample: "Our Wedding Day" },
  { id: "dm-serif-display", name: "DM Serif Display", category: "영문 세리프", family: '"DM Serif Display", serif', sample: "Our Wedding Day" },
  { id: "libre-baskerville", name: "Libre Baskerville", category: "영문 세리프", family: '"Libre Baskerville", serif', sample: "Our Wedding Day" },
  { id: "sacramento", name: "Sacramento", category: "영문 캘리그래피", family: '"Sacramento", cursive', sample: "Happy Wedding Day" },
  { id: "tangerine", name: "Tangerine", category: "영문 캘리그래피", family: '"Tangerine", cursive', sample: "Happy Wedding Day" },
  { id: "pinyon-script", name: "Pinyon Script", category: "영문 캘리그래피", family: '"Pinyon Script", cursive', sample: "Happy Wedding Day" },
  { id: "italianno", name: "Italianno", category: "영문 캘리그래피", family: '"Italianno", cursive', sample: "Happy Wedding Day" },
  { id: "montserrat", name: "Montserrat", category: "영문 모던", family: '"Montserrat", sans-serif', sample: "Our Wedding Day" },
  { id: "raleway", name: "Raleway", category: "영문 모던", family: '"Raleway", sans-serif', sample: "Our Wedding Day" },
  { id: "jost", name: "Jost", category: "영문 모던", family: '"Jost", sans-serif', sample: "Our Wedding Day" },
];
export const HERO_FONT_STYLESHEET = "https://fonts.googleapis.com/css2?family=Alex+Brush&family=Allura&family=Cormorant+Garamond:wght@400;500;600;700&family=Dancing+Script:wght@400;500;600;700&family=Gowun+Batang:wght@400;700&family=Gowun+Dodum&family=Great+Vibes&family=Nanum+Myeongjo:wght@400;700;800&family=Noto+Sans+KR:wght@400;500;600;700&family=Noto+Serif+KR:wght@400;500;600;700&family=Parisienne&family=Playfair+Display:wght@400;500;600;700&family=Hahmlet:wght@400;500;600;700&family=Song+Myung&family=Nanum+Pen+Script&family=Nanum+Brush+Script&family=Gaegu:wght@400;700&family=Hi+Melody&family=IBM+Plex+Sans+KR:wght@400;500;600;700&family=Cinzel:wght@400;500;600;700&family=Bodoni+Moda:wght@400;500;600;700&family=DM+Serif+Display&family=Libre+Baskerville:wght@400;700&family=Sacramento&family=Tangerine:wght@400;700&family=Pinyon+Script&family=Italianno&family=Montserrat:wght@400;500;600;700&family=Raleway:wght@400;500;600;700&family=Jost:wght@400;500;600;700&display=swap";
export const getHeroFont = (id) => HERO_FONTS.find((font) => font.id === id) || HERO_FONTS[0];
