const { PGlite } = require('@electric-sql/pglite');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { randomUUID, createHash } = require('node:crypto');
(async () => {
  const db = new PGlite();
  await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create table auth.users(id uuid primary key, raw_user_meta_data jsonb default '{}');
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;`);
  await db.exec(fs.readFileSync(__dirname + '/../../supabase/migrations/202609090001_initial_event_platform.sql','utf8').replace('create extension if not exists pgcrypto;', ''));
  const migration = fs.readFileSync(__dirname + '/../../supabase/migrations/202609110001_invitation_gallery.sql','utf8');
  await db.exec(migration);
  await db.exec(migration); // Safe to rerun when applying via the SQL editor.
  const owner = randomUUID(), other = randomUUID(), event = randomUUID();
  await db.query('insert into auth.users(id) values ($1),($2)', [owner, other]);
  await db.query("insert into events(id,owner_id,kind,slug,title) values ($1,$2,'wedding','test-gallery','Gallery')", [event,owner]);
  const mutate = async (action, data = {}, user = owner) => (await db.query('select mutate_invitation_gallery($1,$2,$3,$4) result',[event,user,action,JSON.stringify(data)])).rows[0].result;
  const hash = x => createHash('sha256').update(String(x)).digest('hex');
  await assert.rejects(() => mutate('reserve',{hashes:[hash(1)]},other), /GALLERY_FORBIDDEN/);
  const first = await mutate('reserve',{hashes:[hash(1),hash(1),hash(2)]});
  assert.equal(first.length,2);
  assert.ok(first[0].storage_path.startsWith(owner + '/gallery/' + event + '/'));
  assert.equal((await mutate('reserve',{hashes:[hash(1)]}))[0].id,first[0].id);
  await mutate('begin',{id:first[0].id});
  await assert.rejects(() => mutate('begin',{id:first[0].id}), /GALLERY_BUSY/);
  await assert.rejects(() => mutate('delete',{id:first[0].id}), /GALLERY_BUSY/);
  await mutate('finish',{id:first[0].id});
  await mutate('begin',{id:first[1].id}); await mutate('finish',{id:first[1].id});
  const original = first.map(photo=>photo.id), reversed = [...original].reverse();
  await mutate('reorder',{ids:reversed,expected:original});
  const ordered = (await db.query("select id from event_media where event_id=$1 and gallery_state='ready' order by sort_order,id",[event])).rows.map(row=>row.id);
  assert.deepEqual(ordered,reversed);
  await assert.rejects(() => mutate('reorder',{ids:original,expected:original}),/GALLERY_CONFLICT/);
  await assert.rejects(() => mutate('reorder',{ids:[reversed[0],reversed[0]],expected:reversed}),/GALLERY_INVALID/);
  await mutate('reserve',{hashes:Array.from({length:17},(_,i)=>hash(i+3))});
  const races = await Promise.allSettled([mutate('reserve',{hashes:[hash(20)]}),mutate('reserve',{hashes:[hash(21)]})]);
  assert.equal(races.filter(r=>r.status==='fulfilled').length,1);
  assert.match(races.find(r=>r.status==='rejected').reason.message,/GALLERY_LIMIT/);
  assert.equal((await db.query('select count(*)::int n from event_media')).rows[0].n,20);
  await assert.rejects(()=>mutate('reserve',{hashes:[hash(22),hash(23)]}),/GALLERY_LIMIT/);
  assert.equal((await db.query('select count(*)::int n from event_media')).rows[0].n,20);
  await assert.rejects(()=>mutate('purge',{id:first[0].id}),/GALLERY_CONFLICT/);
  await mutate('delete',{id:first[0].id});
  assert.equal((await db.query('select gallery_state from event_media where id=$1',[first[0].id])).rows[0].gallery_state,'deleting');
  await mutate('purge',{id:first[0].id});
  await db.exec("update event_media set gallery_updated_at=now()-interval '16 minutes' where gallery_state='pending'");
  await mutate('expire');
  assert.equal((await db.query("select count(*)::int n from event_media where gallery_state='ready'")).rows[0].n,1);
  assert.equal((await db.query("select count(*)::int n from event_media where gallery_state='deleting'")).rows[0].n,18);
  await db.exec('grant usage on schema public,auth to authenticated; grant select,insert,update,delete on event_media to authenticated;');
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
  await db.exec('set role authenticated');
  await assert.rejects(()=>mutate('reserve',{hashes:[hash(30)]}),/permission denied/);
  assert.equal((await db.query("update event_media set gallery_state='ready' where gallery_state='deleting' returning id")).rows.length,0);
  await db.exec('reset role');
  await db.query('delete from events where id=$1',[event]);
  assert.equal((await db.query('select count(*)::int n from gallery_storage_cleanup')).rows[0].n,19);
  await db.close();
  console.log('PASS PostgreSQL: migration rerun, ownership, deduplication, upload lease, atomic 20 limit, competing reserves, persisted order/conflict, safe deletion, expired cleanup, RLS/RPC permissions.');
})().catch(error=>{console.error(error);process.exitCode=1;});
