-- Admin-managed event type matrix. Existing invitation data remains unchanged.
create table if not exists public.event_type_configs (
  kind text primary key check (kind ~ '^[a-z][a-z0-9_]{1,49}$'),
  label text not null check (char_length(label) between 1 and 60),
  is_visible boolean not null default true,
  sort_order integer not null default 0,
  fields jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.event_type_configs enable row level security;

-- API reads/writes this table only after admin authentication.
-- RLS remains enabled; these grants do not create a public RLS policy.
grant select, insert, update, delete on table public.event_type_configs to authenticated;
grant select, insert, update, delete on table public.event_type_configs to service_role;

insert into public.event_type_configs(kind,label,is_visible,sort_order,fields) values
('wedding','결혼식',true,10,'{"subject":{"state":"required","label":"신랑·신부"},"host":{"state":"none","label":"주최자"},"schedule":{"state":"required","label":"예식 일시"},"venue":{"state":"required","label":"예식 장소"},"message":{"state":"optional","label":"초대 글"},"contacts":{"state":"optional","label":"연락처","roles":[{"key":"groom","label":"신랑"},{"key":"bride","label":"신부"},{"key":"groom_father","label":"신랑 아버지"},{"key":"groom_mother","label":"신랑 어머니"},{"key":"bride_father","label":"신부 아버지"},{"key":"bride_mother","label":"신부 어머니"}]},"gallery":{"state":"optional","label":"갤러리"},"accounts":{"state":"optional","label":"마음 전하실 곳","groups":[{"key":"groom","label":"신랑 측"},{"key":"bride","label":"신부 측"}]},"transport":{"state":"optional","label":"교통·주차"},"notice":{"state":"optional","label":"공지사항"},"rsvp":{"state":"optional","label":"참석 여부"},"guestbook":{"state":"optional","label":"방명록"},"parents_intro":{"state":"none","label":"부모 소개"},"timeline":{"state":"none","label":"성장 기록"}}'),
('first_birthday','돌잔치',true,20,'{"subject":{"state":"required","label":"아이"},"host":{"state":"optional","label":"부모"},"schedule":{"state":"required","label":"행사 일시"},"venue":{"state":"required","label":"장소"},"message":{"state":"optional","label":"초대 글"},"contacts":{"state":"optional","label":"부모 연락처","roles":[{"key":"parent1","label":"아빠"},{"key":"parent2","label":"엄마"}]},"gallery":{"state":"optional","label":"갤러리"},"accounts":{"state":"optional","label":"마음 전하실 곳","groups":[{"key":"parent1","label":"아빠 측"},{"key":"parent2","label":"엄마 측"}]},"transport":{"state":"optional","label":"교통·주차"},"notice":{"state":"optional","label":"공지사항"},"rsvp":{"state":"optional","label":"참석 여부"},"guestbook":{"state":"optional","label":"방명록"},"parents_intro":{"state":"optional","label":"부모 소개"},"timeline":{"state":"optional","label":"성장 기록"}}'),
('birthday','생일',true,30,'{"subject":{"state":"required","label":"주인공"},"host":{"state":"optional","label":"주최자"},"schedule":{"state":"required","label":"행사 일시"},"venue":{"state":"required","label":"장소"},"message":{"state":"optional","label":"초대 글"},"contacts":{"state":"optional","label":"연락처","roles":[{"key":"subject","label":"주인공"},{"key":"host","label":"주최자"}]},"gallery":{"state":"optional","label":"갤러리"},"accounts":{"state":"optional","label":"마음 전하실 곳","groups":[{"key":"host","label":"주최자"}]},"transport":{"state":"optional","label":"교통·주차"},"notice":{"state":"optional","label":"공지사항"},"rsvp":{"state":"optional","label":"참석 여부"},"guestbook":{"state":"optional","label":"방명록"},"parents_intro":{"state":"none","label":"부모 소개"},"timeline":{"state":"none","label":"성장 기록"}}'),
('milestone_birthday','환갑·칠순·팔순',true,40,'{"subject":{"state":"required","label":"주인공"},"host":{"state":"optional","label":"가족·주최자"},"schedule":{"state":"required","label":"행사 일시"},"venue":{"state":"required","label":"장소"},"message":{"state":"optional","label":"초대 글"},"contacts":{"state":"optional","label":"연락처","roles":[{"key":"host1","label":"가족·주최자 1"},{"key":"host2","label":"가족·주최자 2"}]},"gallery":{"state":"optional","label":"갤러리"},"accounts":{"state":"optional","label":"마음 전하실 곳","groups":[{"key":"host","label":"가족·주최자"}]},"transport":{"state":"optional","label":"교통·주차"},"notice":{"state":"optional","label":"공지사항"},"rsvp":{"state":"optional","label":"참석 여부"},"guestbook":{"state":"optional","label":"방명록"},"parents_intro":{"state":"none","label":"부모 소개"},"timeline":{"state":"none","label":"성장 기록"}}'),
('gathering','모임·행사',true,50,'{"subject":{"state":"none","label":"주인공"},"host":{"state":"optional","label":"주최자·담당자"},"schedule":{"state":"required","label":"행사 일시"},"venue":{"state":"required","label":"장소"},"message":{"state":"optional","label":"행사 안내"},"contacts":{"state":"optional","label":"연락처","roles":[{"key":"organizer","label":"주최자·담당자"}]},"gallery":{"state":"optional","label":"갤러리"},"accounts":{"state":"optional","label":"회비·계좌","groups":[{"key":"organizer","label":"회비·계좌"}]},"transport":{"state":"optional","label":"교통·주차"},"notice":{"state":"optional","label":"공지사항"},"rsvp":{"state":"optional","label":"참석 여부"},"guestbook":{"state":"optional","label":"방명록"},"parents_intro":{"state":"none","label":"부모 소개"},"timeline":{"state":"none","label":"성장 기록"}}'),
('opening','개업·오픈',true,60,'{"subject":{"state":"none","label":"주인공"},"host":{"state":"optional","label":"대표자·담당자"},"schedule":{"state":"required","label":"오픈 일시"},"venue":{"state":"required","label":"매장·장소"},"message":{"state":"optional","label":"초대 글"},"contacts":{"state":"optional","label":"연락처","roles":[{"key":"representative","label":"대표자"},{"key":"manager","label":"담당자"}]},"gallery":{"state":"optional","label":"갤러리"},"accounts":{"state":"optional","label":"계좌","groups":[{"key":"business","label":"사업자·매장"}]},"transport":{"state":"optional","label":"교통·주차"},"notice":{"state":"optional","label":"공지사항"},"rsvp":{"state":"optional","label":"참석 여부"},"guestbook":{"state":"optional","label":"방명록"},"parents_intro":{"state":"none","label":"부모 소개"},"timeline":{"state":"none","label":"성장 기록"}}')
on conflict (kind) do update set
  label=excluded.label,
  is_visible=excluded.is_visible,
  sort_order=excluded.sort_order,
  fields=excluded.fields,
  updated_at=now();
